# Generated by Django 2.0.13 on 2019-03-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_auto_20190302_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'User')], max_length=1),
        ),
    ]
