# Generated by Django 2.0.13 on 2019-03-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0004_auto_20190302_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_type',
            field=models.CharField(choices=[('1', 'Admin'), ('2', 'User')], default='2', max_length=1),
        ),
    ]
