# Generated by Django 2.0.13 on 2019-03-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='admin_id',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='admin_id',
            new_name='admin',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='cat_id',
            new_name='cat',
        ),
    ]
