# Generated by Django 2.0.13 on 2019-03-06 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_auto_20190305_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.Category'),
        ),
    ]
