# Generated by Django 2.0.13 on 2019-03-08 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_auto_20190307_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.TextField(),
        ),
    ]
