# Generated by Django 2.0.13 on 2019-03-14 09:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_auto_20190305_1451'),
        ('master', '0005_auto_20190308_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('prod_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.Products')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.Users')),
            ],
        ),
    ]
