# Generated by Django 2.0.13 on 2019-03-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_user',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
