# Generated by Django 2.0.13 on 2019-03-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_cart_user_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart_user',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
