# Generated by Django 2.0.13 on 2019-03-14 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0008_auto_20190314_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart_user',
            old_name='prod_id',
            new_name='prod',
        ),
        migrations.RenameField(
            model_name='cart_user',
            old_name='user_id',
            new_name='user',
        ),
    ]
