# Generated by Django 2.0.13 on 2019-03-25 09:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0005_auto_20190305_1451'),
        ('master', '0009_auto_20190314_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_user_logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('prod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.Products')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.Users')),
            ],
        ),
    ]
